window.esdocSearchIndex = [
  [
    "libquassel/src/alias.js~aliasitem",
    "class/src/alias.js~AliasItem.html",
    "<span>AliasItem</span> <span class=\"search-result-import-path\">libquassel/src/alias.js</span>",
    "class"
  ],
  [
    "libquassel/src/bufferview.js~bufferview",
    "class/src/bufferview.js~BufferView.html",
    "<span>BufferView</span> <span class=\"search-result-import-path\">libquassel/src/bufferview.js</span>",
    "class"
  ],
  [
    "libquassel/src/libquassel.js~client",
    "class/src/libquassel.js~Client.html",
    "<span>Client</span> <span class=\"search-result-import-path\">libquassel/src/libquassel.js</span>",
    "class"
  ],
  [
    "libquassel/src/network.js~connectionstates",
    "variable/index.html#static-variable-ConnectionStates",
    "<span>ConnectionStates</span> <span class=\"search-result-import-path\">libquassel/src/network.js</span>",
    "variable"
  ],
  [
    "libquassel/src/request.js~core",
    "class/src/request.js~Core.html",
    "<span>Core</span> <span class=\"search-result-import-path\">libquassel/src/request.js</span>",
    "class"
  ],
  [
    "libquassel/src/libquassel.js~eventemitter",
    "variable/index.html#static-variable-EventEmitter",
    "<span>EventEmitter</span> <span class=\"search-result-import-path\">libquassel/src/libquassel.js</span>",
    "variable"
  ],
  [
    "libquassel/src/libquassel.js~features",
    "variable/index.html#static-variable-Features",
    "<span>Features</span> <span class=\"search-result-import-path\">libquassel/src/libquassel.js</span>",
    "variable"
  ],
  [
    "libquassel/src/message.js~flags",
    "variable/index.html#static-variable-Flags",
    "<span>Flags</span> <span class=\"search-result-import-path\">libquassel/src/message.js</span>",
    "variable"
  ],
  [
    "libquassel/src/message.js~highlightmodes",
    "variable/index.html#static-variable-HighlightModes",
    "<span>HighlightModes</span> <span class=\"search-result-import-path\">libquassel/src/message.js</span>",
    "variable"
  ],
  [
    "libquassel/src/buffer.js~ircbuffer",
    "class/src/buffer.js~IRCBuffer.html",
    "<span>IRCBuffer</span> <span class=\"search-result-import-path\">libquassel/src/buffer.js</span>",
    "class"
  ],
  [
    "libquassel/src/buffer.js~ircbuffercollection",
    "class/src/buffer.js~IRCBufferCollection.html",
    "<span>IRCBufferCollection</span> <span class=\"search-result-import-path\">libquassel/src/buffer.js</span>",
    "class"
  ],
  [
    "libquassel/src/buffer.js~ircbufferuser",
    "class/src/buffer.js~IRCBufferUser.html",
    "<span>IRCBufferUser</span> <span class=\"search-result-import-path\">libquassel/src/buffer.js</span>",
    "class"
  ],
  [
    "libquassel/src/message.js~ircmessage",
    "class/src/message.js~IRCMessage.html",
    "<span>IRCMessage</span> <span class=\"search-result-import-path\">libquassel/src/message.js</span>",
    "class"
  ],
  [
    "libquassel/src/user.js~ircuser",
    "class/src/user.js~IRCUser.html",
    "<span>IRCUser</span> <span class=\"search-result-import-path\">libquassel/src/user.js</span>",
    "class"
  ],
  [
    "libquassel/src/identity.js~identity",
    "class/src/identity.js~Identity.html",
    "<span>Identity</span> <span class=\"search-result-import-path\">libquassel/src/identity.js</span>",
    "class"
  ],
  [
    "libquassel/src/ignore.js~ignoreitem",
    "class/src/ignore.js~IgnoreItem.html",
    "<span>IgnoreItem</span> <span class=\"search-result-import-path\">libquassel/src/ignore.js</span>",
    "class"
  ],
  [
    "libquassel/src/ignore.js~ignorelist",
    "class/src/ignore.js~IgnoreList.html",
    "<span>IgnoreList</span> <span class=\"search-result-import-path\">libquassel/src/ignore.js</span>",
    "class"
  ],
  [
    "libquassel/src/ignore.js~ignoretypes",
    "variable/index.html#static-variable-IgnoreTypes",
    "<span>IgnoreTypes</span> <span class=\"search-result-import-path\">libquassel/src/ignore.js</span>",
    "variable"
  ],
  [
    "libquassel/src/network.js~network",
    "class/src/network.js~Network.html",
    "<span>Network</span> <span class=\"search-result-import-path\">libquassel/src/network.js</span>",
    "class"
  ],
  [
    "libquassel/src/network.js~networkcollection",
    "class/src/network.js~NetworkCollection.html",
    "<span>NetworkCollection</span> <span class=\"search-result-import-path\">libquassel/src/network.js</span>",
    "class"
  ],
  [
    "libquassel/src/ignore.js~scopetypes",
    "variable/index.html#static-variable-ScopeTypes",
    "<span>ScopeTypes</span> <span class=\"search-result-import-path\">libquassel/src/ignore.js</span>",
    "variable"
  ],
  [
    "libquassel/src/ignore.js~serializable",
    "variable/index.html#static-variable-Serializable",
    "<span>Serializable</span> <span class=\"search-result-import-path\">libquassel/src/ignore.js</span>",
    "variable"
  ],
  [
    "libquassel/src/network.js~server",
    "class/src/network.js~Server.html",
    "<span>Server</span> <span class=\"search-result-import-path\">libquassel/src/network.js</span>",
    "class"
  ],
  [
    "libquassel/src/ignore.js~strictnesstypes",
    "variable/index.html#static-variable-StrictnessTypes",
    "<span>StrictnessTypes</span> <span class=\"search-result-import-path\">libquassel/src/ignore.js</span>",
    "variable"
  ],
  [
    "libquassel/src/buffer.js~types",
    "variable/index.html#static-variable-Types",
    "<span>Types</span> <span class=\"search-result-import-path\">libquassel/src/buffer.js</span>",
    "variable"
  ],
  [
    "libquassel/src/message.js~types",
    "variable/index.html#static-variable-Types",
    "<span>Types</span> <span class=\"search-result-import-path\">libquassel/src/message.js</span>",
    "variable"
  ],
  [
    "libquassel/src/request.js~types",
    "variable/index.html#static-variable-Types",
    "<span>Types</span> <span class=\"search-result-import-path\">libquassel/src/request.js</span>",
    "variable"
  ],
  [
    "libquassel/src/websocket.js~websocketstream",
    "class/src/websocket.js~WebSocketStream.html",
    "<span>WebSocketStream</span> <span class=\"search-result-import-path\">libquassel/src/websocket.js</span>",
    "class"
  ],
  [
    "libquassel/src/alias.js~toarray",
    "function/index.html#static-function-toArray",
    "<span>toArray</span> <span class=\"search-result-import-path\">libquassel/src/alias.js</span>",
    "function"
  ],
  [
    "libquassel/src/alias.js~tocoreobject",
    "function/index.html#static-function-toCoreObject",
    "<span>toCoreObject</span> <span class=\"search-result-import-path\">libquassel/src/alias.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/alias.js",
    "file/src/alias.js.html",
    "src/alias.js",
    "file"
  ],
  [
    "src/alias.js~aliasitem#constructor",
    "class/src/alias.js~AliasItem.html#instance-constructor-constructor",
    "src/alias.js~AliasItem#constructor",
    "method"
  ],
  [
    "src/alias.js~aliasitem#expansion",
    "class/src/alias.js~AliasItem.html#instance-member-expansion",
    "src/alias.js~AliasItem#expansion",
    "member"
  ],
  [
    "src/alias.js~aliasitem#name",
    "class/src/alias.js~AliasItem.html#instance-member-name",
    "src/alias.js~AliasItem#name",
    "member"
  ],
  [
    "src/buffer.js",
    "file/src/buffer.js.html",
    "src/buffer.js",
    "file"
  ],
  [
    "src/buffer.js~bufferinfo",
    "typedef/index.html#static-typedef-BufferInfo",
    "src/buffer.js~BufferInfo",
    "typedef"
  ],
  [
    "src/buffer.js~ircbuffer#_name",
    "class/src/buffer.js~IRCBuffer.html#instance-member-_name",
    "src/buffer.js~IRCBuffer#_name",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#_updatefirstandlast",
    "class/src/buffer.js~IRCBuffer.html#instance-method-_updateFirstAndLast",
    "src/buffer.js~IRCBuffer#_updateFirstAndLast",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#addmessage",
    "class/src/buffer.js~IRCBuffer.html#instance-method-addMessage",
    "src/buffer.js~IRCBuffer#addMessage",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#adduser",
    "class/src/buffer.js~IRCBuffer.html#instance-method-addUser",
    "src/buffer.js~IRCBuffer#addUser",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#addusermode",
    "class/src/buffer.js~IRCBuffer.html#instance-method-addUserMode",
    "src/buffer.js~IRCBuffer#addUserMode",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#clearmessages",
    "class/src/buffer.js~IRCBuffer.html#instance-method-clearMessages",
    "src/buffer.js~IRCBuffer#clearMessages",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#constructor",
    "class/src/buffer.js~IRCBuffer.html#instance-constructor-constructor",
    "src/buffer.js~IRCBuffer#constructor",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#deletemessage",
    "class/src/buffer.js~IRCBuffer.html#instance-method-deleteMessage",
    "src/buffer.js~IRCBuffer#deleteMessage",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#firstmessage",
    "class/src/buffer.js~IRCBuffer.html#instance-get-firstMessage",
    "src/buffer.js~IRCBuffer#firstMessage",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#firstmessageid",
    "class/src/buffer.js~IRCBuffer.html#instance-member-firstMessageId",
    "src/buffer.js~IRCBuffer#firstMessageId",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#getbufferinfo",
    "class/src/buffer.js~IRCBuffer.html#instance-method-getBufferInfo",
    "src/buffer.js~IRCBuffer#getBufferInfo",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#group",
    "class/src/buffer.js~IRCBuffer.html#instance-member-group",
    "src/buffer.js~IRCBuffer#group",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#hasuser",
    "class/src/buffer.js~IRCBuffer.html#instance-method-hasUser",
    "src/buffer.js~IRCBuffer#hasUser",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#id",
    "class/src/buffer.js~IRCBuffer.html#instance-member-id",
    "src/buffer.js~IRCBuffer#id",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#isactive",
    "class/src/buffer.js~IRCBuffer.html#instance-member-isActive",
    "src/buffer.js~IRCBuffer#isActive",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#ischannel",
    "class/src/buffer.js~IRCBuffer.html#instance-member-isChannel",
    "src/buffer.js~IRCBuffer#isChannel",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#islast",
    "class/src/buffer.js~IRCBuffer.html#instance-method-isLast",
    "src/buffer.js~IRCBuffer#isLast",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#isstatusbuffer",
    "class/src/buffer.js~IRCBuffer.html#instance-member-isStatusBuffer",
    "src/buffer.js~IRCBuffer#isStatusBuffer",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#lastmessage",
    "class/src/buffer.js~IRCBuffer.html#instance-get-lastMessage",
    "src/buffer.js~IRCBuffer#lastMessage",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#lastmessageid",
    "class/src/buffer.js~IRCBuffer.html#instance-member-lastMessageId",
    "src/buffer.js~IRCBuffer#lastMessageId",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#messages",
    "class/src/buffer.js~IRCBuffer.html#instance-member-messages",
    "src/buffer.js~IRCBuffer#messages",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#name",
    "class/src/buffer.js~IRCBuffer.html#instance-set-name",
    "src/buffer.js~IRCBuffer#name",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#name",
    "class/src/buffer.js~IRCBuffer.html#instance-get-name",
    "src/buffer.js~IRCBuffer#name",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#network",
    "class/src/buffer.js~IRCBuffer.html#instance-member-network",
    "src/buffer.js~IRCBuffer#network",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#removeuser",
    "class/src/buffer.js~IRCBuffer.html#instance-method-removeUser",
    "src/buffer.js~IRCBuffer#removeUser",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#removeusermode",
    "class/src/buffer.js~IRCBuffer.html#instance-method-removeUserMode",
    "src/buffer.js~IRCBuffer#removeUserMode",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#tostring",
    "class/src/buffer.js~IRCBuffer.html#instance-method-toString",
    "src/buffer.js~IRCBuffer#toString",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#trimmessages",
    "class/src/buffer.js~IRCBuffer.html#instance-method-trimMessages",
    "src/buffer.js~IRCBuffer#trimMessages",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#type",
    "class/src/buffer.js~IRCBuffer.html#instance-member-type",
    "src/buffer.js~IRCBuffer#type",
    "member"
  ],
  [
    "src/buffer.js~ircbuffer#update",
    "class/src/buffer.js~IRCBuffer.html#instance-method-update",
    "src/buffer.js~IRCBuffer#update",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#updateusermaps",
    "class/src/buffer.js~IRCBuffer.html#instance-method-updateUserMaps",
    "src/buffer.js~IRCBuffer#updateUserMaps",
    "method"
  ],
  [
    "src/buffer.js~ircbuffer#users",
    "class/src/buffer.js~IRCBuffer.html#instance-member-users",
    "src/buffer.js~IRCBuffer#users",
    "member"
  ],
  [
    "src/buffer.js~ircbuffercollection#_map_buffer_ids",
    "class/src/buffer.js~IRCBufferCollection.html#instance-member-_map_buffer_ids",
    "src/buffer.js~IRCBufferCollection#_map_buffer_ids",
    "member"
  ],
  [
    "src/buffer.js~ircbuffercollection#add",
    "class/src/buffer.js~IRCBufferCollection.html#instance-method-add",
    "src/buffer.js~IRCBufferCollection#add",
    "method"
  ],
  [
    "src/buffer.js~ircbuffercollection#clear",
    "class/src/buffer.js~IRCBufferCollection.html#instance-method-clear",
    "src/buffer.js~IRCBufferCollection#clear",
    "method"
  ],
  [
    "src/buffer.js~ircbuffercollection#constructor",
    "class/src/buffer.js~IRCBufferCollection.html#instance-constructor-constructor",
    "src/buffer.js~IRCBufferCollection#constructor",
    "method"
  ],
  [
    "src/buffer.js~ircbuffercollection#delete",
    "class/src/buffer.js~IRCBufferCollection.html#instance-method-delete",
    "src/buffer.js~IRCBufferCollection#delete",
    "method"
  ],
  [
    "src/buffer.js~ircbuffercollection#get",
    "class/src/buffer.js~IRCBufferCollection.html#instance-method-get",
    "src/buffer.js~IRCBufferCollection#get",
    "method"
  ],
  [
    "src/buffer.js~ircbuffercollection#has",
    "class/src/buffer.js~IRCBufferCollection.html#instance-method-has",
    "src/buffer.js~IRCBufferCollection#has",
    "method"
  ],
  [
    "src/buffer.js~ircbuffercollection#move",
    "class/src/buffer.js~IRCBufferCollection.html#instance-method-move",
    "src/buffer.js~IRCBufferCollection#move",
    "method"
  ],
  [
    "src/buffer.js~ircbuffercollection#set",
    "class/src/buffer.js~IRCBufferCollection.html#instance-method-set",
    "src/buffer.js~IRCBufferCollection#set",
    "method"
  ],
  [
    "src/buffer.js~ircbufferuser#_modes",
    "class/src/buffer.js~IRCBufferUser.html#instance-member-_modes",
    "src/buffer.js~IRCBufferUser#_modes",
    "member"
  ],
  [
    "src/buffer.js~ircbufferuser#constructor",
    "class/src/buffer.js~IRCBufferUser.html#instance-constructor-constructor",
    "src/buffer.js~IRCBufferUser#constructor",
    "method"
  ],
  [
    "src/buffer.js~ircbufferuser#hasmode",
    "class/src/buffer.js~IRCBufferUser.html#instance-method-hasMode",
    "src/buffer.js~IRCBufferUser#hasMode",
    "method"
  ],
  [
    "src/buffer.js~ircbufferuser#isadmin",
    "class/src/buffer.js~IRCBufferUser.html#instance-member-isAdmin",
    "src/buffer.js~IRCBufferUser#isAdmin",
    "member"
  ],
  [
    "src/buffer.js~ircbufferuser#ishalfop",
    "class/src/buffer.js~IRCBufferUser.html#instance-member-isHalfOp",
    "src/buffer.js~IRCBufferUser#isHalfOp",
    "member"
  ],
  [
    "src/buffer.js~ircbufferuser#isop",
    "class/src/buffer.js~IRCBufferUser.html#instance-member-isOp",
    "src/buffer.js~IRCBufferUser#isOp",
    "member"
  ],
  [
    "src/buffer.js~ircbufferuser#isowner",
    "class/src/buffer.js~IRCBufferUser.html#instance-member-isOwner",
    "src/buffer.js~IRCBufferUser#isOwner",
    "member"
  ],
  [
    "src/buffer.js~ircbufferuser#isvoiced",
    "class/src/buffer.js~IRCBufferUser.html#instance-member-isVoiced",
    "src/buffer.js~IRCBufferUser#isVoiced",
    "member"
  ],
  [
    "src/buffer.js~ircbufferuser#modes",
    "class/src/buffer.js~IRCBufferUser.html#instance-get-modes",
    "src/buffer.js~IRCBufferUser#modes",
    "member"
  ],
  [
    "src/buffer.js~ircbufferuser#modes",
    "class/src/buffer.js~IRCBufferUser.html#instance-set-modes",
    "src/buffer.js~IRCBufferUser#modes",
    "member"
  ],
  [
    "src/buffer.js~ircbufferuser#user",
    "class/src/buffer.js~IRCBufferUser.html#instance-member-user",
    "src/buffer.js~IRCBufferUser#user",
    "member"
  ],
  [
    "src/bufferview.js",
    "file/src/bufferview.js.html",
    "src/bufferview.js",
    "file"
  ],
  [
    "src/bufferview.js~bufferview#bufferlist",
    "class/src/bufferview.js~BufferView.html#instance-member-BufferList",
    "src/bufferview.js~BufferView#BufferList",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#removedbuffers",
    "class/src/bufferview.js~BufferView.html#instance-member-RemovedBuffers",
    "src/bufferview.js~BufferView#RemovedBuffers",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#temporarilyremovedbuffers",
    "class/src/bufferview.js~BufferView.html#instance-member-TemporarilyRemovedBuffers",
    "src/bufferview.js~BufferView#TemporarilyRemovedBuffers",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#addbuffer",
    "class/src/bufferview.js~BufferView.html#instance-method-addBuffer",
    "src/bufferview.js~BufferView#addBuffer",
    "method"
  ],
  [
    "src/bufferview.js~bufferview#addnewbuffersautomatically",
    "class/src/bufferview.js~BufferView.html#instance-member-addNewBuffersAutomatically",
    "src/bufferview.js~BufferView#addNewBuffersAutomatically",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#allowedbuffertypes",
    "class/src/bufferview.js~BufferView.html#instance-member-allowedBufferTypes",
    "src/bufferview.js~BufferView#allowedBufferTypes",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#bufferviewname",
    "class/src/bufferview.js~BufferView.html#instance-member-bufferViewName",
    "src/bufferview.js~BufferView#bufferViewName",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#comparator",
    "class/src/bufferview.js~BufferView.html#instance-method-comparator",
    "src/bufferview.js~BufferView#comparator",
    "method"
  ],
  [
    "src/bufferview.js~bufferview#constructor",
    "class/src/bufferview.js~BufferView.html#instance-constructor-constructor",
    "src/bufferview.js~BufferView#constructor",
    "method"
  ],
  [
    "src/bufferview.js~bufferview#disabledecoration",
    "class/src/bufferview.js~BufferView.html#instance-member-disableDecoration",
    "src/bufferview.js~BufferView#disableDecoration",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#hideinactivebuffers",
    "class/src/bufferview.js~BufferView.html#instance-member-hideInactiveBuffers",
    "src/bufferview.js~BufferView#hideInactiveBuffers",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#hideinactivenetworks",
    "class/src/bufferview.js~BufferView.html#instance-member-hideInactiveNetworks",
    "src/bufferview.js~BufferView#hideInactiveNetworks",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#id",
    "class/src/bufferview.js~BufferView.html#instance-member-id",
    "src/bufferview.js~BufferView#id",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#ishidden",
    "class/src/bufferview.js~BufferView.html#instance-method-isHidden",
    "src/bufferview.js~BufferView#isHidden",
    "method"
  ],
  [
    "src/bufferview.js~bufferview#ispermanentlyremoved",
    "class/src/bufferview.js~BufferView.html#instance-method-isPermanentlyRemoved",
    "src/bufferview.js~BufferView#isPermanentlyRemoved",
    "method"
  ],
  [
    "src/bufferview.js~bufferview#istemporarilyremoved",
    "class/src/bufferview.js~BufferView.html#instance-method-isTemporarilyRemoved",
    "src/bufferview.js~BufferView#isTemporarilyRemoved",
    "method"
  ],
  [
    "src/bufferview.js~bufferview#minimumactivity",
    "class/src/bufferview.js~BufferView.html#instance-member-minimumActivity",
    "src/bufferview.js~BufferView#minimumActivity",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#movebuffer",
    "class/src/bufferview.js~BufferView.html#instance-method-moveBuffer",
    "src/bufferview.js~BufferView#moveBuffer",
    "method"
  ],
  [
    "src/bufferview.js~bufferview#networkid",
    "class/src/bufferview.js~BufferView.html#instance-member-networkId",
    "src/bufferview.js~BufferView#networkId",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#setpermanentlyremoved",
    "class/src/bufferview.js~BufferView.html#instance-method-setPermanentlyRemoved",
    "src/bufferview.js~BufferView#setPermanentlyRemoved",
    "method"
  ],
  [
    "src/bufferview.js~bufferview#settemporarilyremoved",
    "class/src/bufferview.js~BufferView.html#instance-method-setTemporarilyRemoved",
    "src/bufferview.js~BufferView#setTemporarilyRemoved",
    "method"
  ],
  [
    "src/bufferview.js~bufferview#showsearch",
    "class/src/bufferview.js~BufferView.html#instance-member-showSearch",
    "src/bufferview.js~BufferView#showSearch",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#sortalphabetically",
    "class/src/bufferview.js~BufferView.html#instance-member-sortAlphabetically",
    "src/bufferview.js~BufferView#sortAlphabetically",
    "member"
  ],
  [
    "src/bufferview.js~bufferview#tostring",
    "class/src/bufferview.js~BufferView.html#instance-method-toString",
    "src/bufferview.js~BufferView#toString",
    "method"
  ],
  [
    "src/bufferview.js~bufferview#unhide",
    "class/src/bufferview.js~BufferView.html#instance-method-unhide",
    "src/bufferview.js~BufferView#unhide",
    "method"
  ],
  [
    "src/bufferview.js~bufferview#update",
    "class/src/bufferview.js~BufferView.html#instance-method-update",
    "src/bufferview.js~BufferView#update",
    "method"
  ],
  [
    "src/identity.js",
    "file/src/identity.js.html",
    "src/identity.js",
    "file"
  ],
  [
    "src/identity.js~identity#_nicks",
    "class/src/identity.js~Identity.html#instance-member-_nicks",
    "src/identity.js~Identity#_nicks",
    "member"
  ],
  [
    "src/identity.js~identity#autoawayenabled",
    "class/src/identity.js~Identity.html#instance-member-autoAwayEnabled",
    "src/identity.js~Identity#autoAwayEnabled",
    "member"
  ],
  [
    "src/identity.js~identity#autoawayreason",
    "class/src/identity.js~Identity.html#instance-member-autoAwayReason",
    "src/identity.js~Identity#autoAwayReason",
    "member"
  ],
  [
    "src/identity.js~identity#autoawayreasonenabled",
    "class/src/identity.js~Identity.html#instance-member-autoAwayReasonEnabled",
    "src/identity.js~Identity#autoAwayReasonEnabled",
    "member"
  ],
  [
    "src/identity.js~identity#autoawaytime",
    "class/src/identity.js~Identity.html#instance-member-autoAwayTime",
    "src/identity.js~Identity#autoAwayTime",
    "member"
  ],
  [
    "src/identity.js~identity#awaynick",
    "class/src/identity.js~Identity.html#instance-member-awayNick",
    "src/identity.js~Identity#awayNick",
    "member"
  ],
  [
    "src/identity.js~identity#awaynickenabled",
    "class/src/identity.js~Identity.html#instance-member-awayNickEnabled",
    "src/identity.js~Identity#awayNickEnabled",
    "member"
  ],
  [
    "src/identity.js~identity#awayreason",
    "class/src/identity.js~Identity.html#instance-member-awayReason",
    "src/identity.js~Identity#awayReason",
    "member"
  ],
  [
    "src/identity.js~identity#awayreasonenabled",
    "class/src/identity.js~Identity.html#instance-member-awayReasonEnabled",
    "src/identity.js~Identity#awayReasonEnabled",
    "member"
  ],
  [
    "src/identity.js~identity#constructor",
    "class/src/identity.js~Identity.html#instance-constructor-constructor",
    "src/identity.js~Identity#constructor",
    "method"
  ],
  [
    "src/identity.js~identity#detachawayenabled",
    "class/src/identity.js~Identity.html#instance-member-detachAwayEnabled",
    "src/identity.js~Identity#detachAwayEnabled",
    "member"
  ],
  [
    "src/identity.js~identity#detachawayreason",
    "class/src/identity.js~Identity.html#instance-member-detachAwayReason",
    "src/identity.js~Identity#detachAwayReason",
    "member"
  ],
  [
    "src/identity.js~identity#detachawayreasonenabled",
    "class/src/identity.js~Identity.html#instance-member-detachAwayReasonEnabled",
    "src/identity.js~Identity#detachAwayReasonEnabled",
    "member"
  ],
  [
    "src/identity.js~identity#id",
    "class/src/identity.js~Identity.html#instance-get-id",
    "src/identity.js~Identity#id",
    "member"
  ],
  [
    "src/identity.js~identity#id",
    "class/src/identity.js~Identity.html#instance-set-id",
    "src/identity.js~Identity#id",
    "member"
  ],
  [
    "src/identity.js~identity#ident",
    "class/src/identity.js~Identity.html#instance-member-ident",
    "src/identity.js~Identity#ident",
    "member"
  ],
  [
    "src/identity.js~identity#identityid",
    "class/src/identity.js~Identity.html#instance-member-identityId",
    "src/identity.js~Identity#identityId",
    "member"
  ],
  [
    "src/identity.js~identity#identityname",
    "class/src/identity.js~Identity.html#instance-member-identityName",
    "src/identity.js~Identity#identityName",
    "member"
  ],
  [
    "src/identity.js~identity#kickreason",
    "class/src/identity.js~Identity.html#instance-member-kickReason",
    "src/identity.js~Identity#kickReason",
    "member"
  ],
  [
    "src/identity.js~identity#nickregexes",
    "class/src/identity.js~Identity.html#instance-member-nickRegexes",
    "src/identity.js~Identity#nickRegexes",
    "member"
  ],
  [
    "src/identity.js~identity#nicks",
    "class/src/identity.js~Identity.html#instance-set-nicks",
    "src/identity.js~Identity#nicks",
    "member"
  ],
  [
    "src/identity.js~identity#nicks",
    "class/src/identity.js~Identity.html#instance-get-nicks",
    "src/identity.js~Identity#nicks",
    "member"
  ],
  [
    "src/identity.js~identity#partreason",
    "class/src/identity.js~Identity.html#instance-member-partReason",
    "src/identity.js~Identity#partReason",
    "member"
  ],
  [
    "src/identity.js~identity#quitreason",
    "class/src/identity.js~Identity.html#instance-member-quitReason",
    "src/identity.js~Identity#quitReason",
    "member"
  ],
  [
    "src/identity.js~identity#realname",
    "class/src/identity.js~Identity.html#instance-member-realName",
    "src/identity.js~Identity#realName",
    "member"
  ],
  [
    "src/identity.js~identity#tostring",
    "class/src/identity.js~Identity.html#instance-method-toString",
    "src/identity.js~Identity#toString",
    "method"
  ],
  [
    "src/identity.js~identity#update",
    "class/src/identity.js~Identity.html#instance-method-update",
    "src/identity.js~Identity#update",
    "method"
  ],
  [
    "src/identity.js~identity.create",
    "class/src/identity.js~Identity.html#static-method-create",
    "src/identity.js~Identity.create",
    "method"
  ],
  [
    "src/ignore.js",
    "file/src/ignore.js.html",
    "src/ignore.js",
    "file"
  ],
  [
    "src/ignore.js~ignoreitem#compile",
    "class/src/ignore.js~IgnoreItem.html#instance-method-compile",
    "src/ignore.js~IgnoreItem#compile",
    "method"
  ],
  [
    "src/ignore.js~ignoreitem#constructor",
    "class/src/ignore.js~IgnoreItem.html#instance-constructor-constructor",
    "src/ignore.js~IgnoreItem#constructor",
    "method"
  ],
  [
    "src/ignore.js~ignoreitem#ignorerule",
    "class/src/ignore.js~IgnoreItem.html#instance-member-ignoreRule",
    "src/ignore.js~IgnoreItem#ignoreRule",
    "member"
  ],
  [
    "src/ignore.js~ignoreitem#ignoretype",
    "class/src/ignore.js~IgnoreItem.html#instance-member-ignoreType",
    "src/ignore.js~IgnoreItem#ignoreType",
    "member"
  ],
  [
    "src/ignore.js~ignoreitem#isactive",
    "class/src/ignore.js~IgnoreItem.html#instance-member-isActive",
    "src/ignore.js~IgnoreItem#isActive",
    "member"
  ],
  [
    "src/ignore.js~ignoreitem#isregex",
    "class/src/ignore.js~IgnoreItem.html#instance-member-isRegEx",
    "src/ignore.js~IgnoreItem#isRegEx",
    "member"
  ],
  [
    "src/ignore.js~ignoreitem#matchignore",
    "class/src/ignore.js~IgnoreItem.html#instance-method-matchIgnore",
    "src/ignore.js~IgnoreItem#matchIgnore",
    "method"
  ],
  [
    "src/ignore.js~ignoreitem#matchscope",
    "class/src/ignore.js~IgnoreItem.html#instance-method-matchScope",
    "src/ignore.js~IgnoreItem#matchScope",
    "method"
  ],
  [
    "src/ignore.js~ignoreitem#regexignore",
    "class/src/ignore.js~IgnoreItem.html#instance-member-regexIgnore",
    "src/ignore.js~IgnoreItem#regexIgnore",
    "member"
  ],
  [
    "src/ignore.js~ignoreitem#regexscope",
    "class/src/ignore.js~IgnoreItem.html#instance-member-regexScope",
    "src/ignore.js~IgnoreItem#regexScope",
    "member"
  ],
  [
    "src/ignore.js~ignoreitem#scope",
    "class/src/ignore.js~IgnoreItem.html#instance-member-scope",
    "src/ignore.js~IgnoreItem#scope",
    "member"
  ],
  [
    "src/ignore.js~ignoreitem#scoperule",
    "class/src/ignore.js~IgnoreItem.html#instance-member-scopeRule",
    "src/ignore.js~IgnoreItem#scopeRule",
    "member"
  ],
  [
    "src/ignore.js~ignoreitem#strictness",
    "class/src/ignore.js~IgnoreItem.html#instance-member-strictness",
    "src/ignore.js~IgnoreItem#strictness",
    "member"
  ],
  [
    "src/ignore.js~ignoreitem#tostring",
    "class/src/ignore.js~IgnoreItem.html#instance-method-toString",
    "src/ignore.js~IgnoreItem#toString",
    "method"
  ],
  [
    "src/ignore.js~ignorelist#_export",
    "class/src/ignore.js~IgnoreList.html#instance-method-_export",
    "src/ignore.js~IgnoreList#_export",
    "method"
  ],
  [
    "src/ignore.js~ignorelist#constructor",
    "class/src/ignore.js~IgnoreList.html#instance-constructor-constructor",
    "src/ignore.js~IgnoreList#constructor",
    "method"
  ],
  [
    "src/ignore.js~ignorelist#import",
    "class/src/ignore.js~IgnoreList.html#instance-method-import",
    "src/ignore.js~IgnoreList#import",
    "method"
  ],
  [
    "src/ignore.js~ignorelist#list",
    "class/src/ignore.js~IgnoreList.html#instance-member-list",
    "src/ignore.js~IgnoreList#list",
    "member"
  ],
  [
    "src/ignore.js~ignorelist#matches",
    "class/src/ignore.js~IgnoreList.html#instance-method-matches",
    "src/ignore.js~IgnoreList#matches",
    "method"
  ],
  [
    "src/ignore.js~ignorelist#tostring",
    "class/src/ignore.js~IgnoreList.html#instance-method-toString",
    "src/ignore.js~IgnoreList#toString",
    "method"
  ],
  [
    "src/libquassel.js",
    "file/src/libquassel.js.html",
    "src/libquassel.js",
    "file"
  ],
  [
    "src/libquassel.js~client#aliases",
    "class/src/libquassel.js~Client.html#instance-member-aliases",
    "src/libquassel.js~Client#aliases",
    "member"
  ],
  [
    "src/libquassel.js~client#bufferviews",
    "class/src/libquassel.js~Client.html#instance-member-bufferViews",
    "src/libquassel.js~Client#bufferViews",
    "member"
  ],
  [
    "src/libquassel.js~client#connect",
    "class/src/libquassel.js~Client.html#instance-method-connect",
    "src/libquassel.js~Client#connect",
    "method"
  ],
  [
    "src/libquassel.js~client#connected",
    "class/src/libquassel.js~Client.html#instance-member-connected",
    "src/libquassel.js~Client#connected",
    "member"
  ],
  [
    "src/libquassel.js~client#constructor",
    "class/src/libquassel.js~Client.html#instance-constructor-constructor",
    "src/libquassel.js~Client#constructor",
    "method"
  ],
  [
    "src/libquassel.js~client#core",
    "class/src/libquassel.js~Client.html#instance-member-core",
    "src/libquassel.js~Client#core",
    "member"
  ],
  [
    "src/libquassel.js~client#coredata",
    "class/src/libquassel.js~Client.html#instance-member-coreData",
    "src/libquassel.js~Client#coreData",
    "member"
  ],
  [
    "src/libquassel.js~client#coreinfo",
    "class/src/libquassel.js~Client.html#instance-member-coreInfo",
    "src/libquassel.js~Client#coreInfo",
    "member"
  ],
  [
    "src/libquassel.js~client#disconnect",
    "class/src/libquassel.js~Client.html#instance-method-disconnect",
    "src/libquassel.js~Client#disconnect",
    "method"
  ],
  [
    "src/libquassel.js~client#dispatch",
    "class/src/libquassel.js~Client.html#instance-method-dispatch",
    "src/libquassel.js~Client#dispatch",
    "method"
  ],
  [
    "src/libquassel.js~client#handleclientinitack",
    "class/src/libquassel.js~Client.html#instance-method-handleClientInitAck",
    "src/libquassel.js~Client#handleClientInitAck",
    "method"
  ],
  [
    "src/libquassel.js~client#handleinitdatanetwork",
    "class/src/libquassel.js~Client.html#instance-method-handleInitDataNetwork",
    "src/libquassel.js~Client#handleInitDataNetwork",
    "method"
  ],
  [
    "src/libquassel.js~client#handlemsgtype",
    "class/src/libquassel.js~Client.html#instance-method-handleMsgType",
    "src/libquassel.js~Client#handleMsgType",
    "method"
  ],
  [
    "src/libquassel.js~client#handlesessioninit",
    "class/src/libquassel.js~Client.html#instance-method-handleSessionInit",
    "src/libquassel.js~Client#handleSessionInit",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestruct",
    "class/src/libquassel.js~Client.html#instance-method-handleStruct",
    "src/libquassel.js~Client#handleStruct",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructinitdata",
    "class/src/libquassel.js~Client.html#instance-method-handleStructInitData",
    "src/libquassel.js~Client#handleStructInitData",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructinitdatabuffersyncer",
    "class/src/libquassel.js~Client.html#instance-method-handleStructInitDataBufferSyncer",
    "src/libquassel.js~Client#handleStructInitDataBufferSyncer",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructinitdatabufferviewconfig",
    "class/src/libquassel.js~Client.html#instance-method-handleStructInitDataBufferViewConfig",
    "src/libquassel.js~Client#handleStructInitDataBufferViewConfig",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructinitdataircchannel",
    "class/src/libquassel.js~Client.html#instance-method-handleStructInitDataIrcChannel",
    "src/libquassel.js~Client#handleStructInitDataIrcChannel",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructinitdataircuser",
    "class/src/libquassel.js~Client.html#instance-method-handleStructInitDataIrcUser",
    "src/libquassel.js~Client#handleStructInitDataIrcUser",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructrpccall",
    "class/src/libquassel.js~Client.html#instance-method-handleStructRpcCall",
    "src/libquassel.js~Client#handleStructRpcCall",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructrpccalldisplaymsg",
    "class/src/libquassel.js~Client.html#instance-method-handleStructRpcCallDisplayMsg",
    "src/libquassel.js~Client#handleStructRpcCallDisplayMsg",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructrpccall__objectrenamed__",
    "class/src/libquassel.js~Client.html#instance-method-handleStructRpcCall__objectRenamed__",
    "src/libquassel.js~Client#handleStructRpcCall__objectRenamed__",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructsync",
    "class/src/libquassel.js~Client.html#instance-method-handleStructSync",
    "src/libquassel.js~Client#handleStructSync",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructsyncaliasmanager",
    "class/src/libquassel.js~Client.html#instance-method-handleStructSyncAliasManager",
    "src/libquassel.js~Client#handleStructSyncAliasManager",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructsyncbacklogmanager",
    "class/src/libquassel.js~Client.html#instance-method-handleStructSyncBacklogManager",
    "src/libquassel.js~Client#handleStructSyncBacklogManager",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructsyncbuffersyncer",
    "class/src/libquassel.js~Client.html#instance-method-handleStructSyncBufferSyncer",
    "src/libquassel.js~Client#handleStructSyncBufferSyncer",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructsyncbufferviewconfig",
    "class/src/libquassel.js~Client.html#instance-method-handleStructSyncBufferViewConfig",
    "src/libquassel.js~Client#handleStructSyncBufferViewConfig",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructsyncbufferviewmanager",
    "class/src/libquassel.js~Client.html#instance-method-handleStructSyncBufferViewManager",
    "src/libquassel.js~Client#handleStructSyncBufferViewManager",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructsyncidentity",
    "class/src/libquassel.js~Client.html#instance-method-handleStructSyncIdentity",
    "src/libquassel.js~Client#handleStructSyncIdentity",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructsyncignorelistmanager",
    "class/src/libquassel.js~Client.html#instance-method-handleStructSyncIgnoreListManager",
    "src/libquassel.js~Client#handleStructSyncIgnoreListManager",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructsyncircchannel",
    "class/src/libquassel.js~Client.html#instance-method-handleStructSyncIrcChannel",
    "src/libquassel.js~Client#handleStructSyncIrcChannel",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructsyncircuser",
    "class/src/libquassel.js~Client.html#instance-method-handleStructSyncIrcUser",
    "src/libquassel.js~Client#handleStructSyncIrcUser",
    "method"
  ],
  [
    "src/libquassel.js~client#handlestructsyncnetwork",
    "class/src/libquassel.js~Client.html#instance-method-handleStructSyncNetwork",
    "src/libquassel.js~Client#handleStructSyncNetwork",
    "method"
  ],
  [
    "src/libquassel.js~client#heartbeatinterval",
    "class/src/libquassel.js~Client.html#instance-member-heartbeatInterval",
    "src/libquassel.js~Client#heartbeatInterval",
    "member"
  ],
  [
    "src/libquassel.js~client#identities",
    "class/src/libquassel.js~Client.html#instance-member-identities",
    "src/libquassel.js~Client#identities",
    "member"
  ],
  [
    "src/libquassel.js~client#ignorelist",
    "class/src/libquassel.js~Client.html#instance-member-ignoreList",
    "src/libquassel.js~Client#ignoreList",
    "member"
  ],
  [
    "src/libquassel.js~client#login",
    "class/src/libquassel.js~Client.html#instance-method-login",
    "src/libquassel.js~Client#login",
    "method"
  ],
  [
    "src/libquassel.js~client#logincallback",
    "class/src/libquassel.js~Client.html#instance-member-loginCallback",
    "src/libquassel.js~Client#loginCallback",
    "member"
  ],
  [
    "src/libquassel.js~client#networks",
    "class/src/libquassel.js~Client.html#instance-member-networks",
    "src/libquassel.js~Client#networks",
    "member"
  ],
  [
    "src/libquassel.js~client#options",
    "class/src/libquassel.js~Client.html#instance-member-options",
    "src/libquassel.js~Client#options",
    "member"
  ],
  [
    "src/libquassel.js~client#setupcore",
    "class/src/libquassel.js~Client.html#instance-method-setupCore",
    "src/libquassel.js~Client#setupCore",
    "method"
  ],
  [
    "src/libquassel.js~client#supports",
    "class/src/libquassel.js~Client.html#instance-method-supports",
    "src/libquassel.js~Client#supports",
    "method"
  ],
  [
    "src/libquassel.js~client#usecompression",
    "class/src/libquassel.js~Client.html#instance-member-useCompression",
    "src/libquassel.js~Client#useCompression",
    "member"
  ],
  [
    "src/libquassel.js~event:aliases",
    "typedef/index.html#static-typedef-Event:aliases",
    "src/libquassel.js~Event:aliases",
    "typedef"
  ],
  [
    "src/libquassel.js~event:buffer.activate",
    "typedef/index.html#static-typedef-Event:buffer.activate",
    "src/libquassel.js~Event:buffer.activate",
    "typedef"
  ],
  [
    "src/libquassel.js~event:buffer.backlog",
    "typedef/index.html#static-typedef-Event:buffer.backlog",
    "src/libquassel.js~Event:buffer.backlog",
    "typedef"
  ],
  [
    "src/libquassel.js~event:buffer.deactivate",
    "typedef/index.html#static-typedef-Event:buffer.deactivate",
    "src/libquassel.js~Event:buffer.deactivate",
    "typedef"
  ],
  [
    "src/libquassel.js~event:buffer.lastseen",
    "typedef/index.html#static-typedef-Event:buffer.lastseen",
    "src/libquassel.js~Event:buffer.lastseen",
    "typedef"
  ],
  [
    "src/libquassel.js~event:buffer.markerline",
    "typedef/index.html#static-typedef-Event:buffer.markerline",
    "src/libquassel.js~Event:buffer.markerline",
    "typedef"
  ],
  [
    "src/libquassel.js~event:buffer.merge",
    "typedef/index.html#static-typedef-Event:buffer.merge",
    "src/libquassel.js~Event:buffer.merge",
    "typedef"
  ],
  [
    "src/libquassel.js~event:buffer.message",
    "typedef/index.html#static-typedef-Event:buffer.message",
    "src/libquassel.js~Event:buffer.message",
    "typedef"
  ],
  [
    "src/libquassel.js~event:buffer.read",
    "typedef/index.html#static-typedef-Event:buffer.read",
    "src/libquassel.js~Event:buffer.read",
    "typedef"
  ],
  [
    "src/libquassel.js~event:buffer.remove",
    "typedef/index.html#static-typedef-Event:buffer.remove",
    "src/libquassel.js~Event:buffer.remove",
    "typedef"
  ],
  [
    "src/libquassel.js~event:buffer.rename",
    "typedef/index.html#static-typedef-Event:buffer.rename",
    "src/libquassel.js~Event:buffer.rename",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.addnewbuffersautomatically",
    "typedef/index.html#static-typedef-Event:bufferview.addnewbuffersautomatically",
    "src/libquassel.js~Event:bufferview.addnewbuffersautomatically",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.allowedbuffertypes",
    "typedef/index.html#static-typedef-Event:bufferview.allowedbuffertypes",
    "src/libquassel.js~Event:bufferview.allowedbuffertypes",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.bufferhidden",
    "typedef/index.html#static-typedef-Event:bufferview.bufferhidden",
    "src/libquassel.js~Event:bufferview.bufferhidden",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.bufferunhide",
    "typedef/index.html#static-typedef-Event:bufferview.bufferunhide",
    "src/libquassel.js~Event:bufferview.bufferunhide",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.bufferviewname",
    "typedef/index.html#static-typedef-Event:bufferview.bufferviewname",
    "src/libquassel.js~Event:bufferview.bufferviewname",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.disabledecoration",
    "typedef/index.html#static-typedef-Event:bufferview.disabledecoration",
    "src/libquassel.js~Event:bufferview.disabledecoration",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.hideinactivebuffers",
    "typedef/index.html#static-typedef-Event:bufferview.hideinactivebuffers",
    "src/libquassel.js~Event:bufferview.hideinactivebuffers",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.hideinactivenetworks",
    "typedef/index.html#static-typedef-Event:bufferview.hideinactivenetworks",
    "src/libquassel.js~Event:bufferview.hideinactivenetworks",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.ids",
    "typedef/index.html#static-typedef-Event:bufferview.ids",
    "src/libquassel.js~Event:bufferview.ids",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.init",
    "typedef/index.html#static-typedef-Event:bufferview.init",
    "src/libquassel.js~Event:bufferview.init",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.minimumactivity",
    "typedef/index.html#static-typedef-Event:bufferview.minimumactivity",
    "src/libquassel.js~Event:bufferview.minimumactivity",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.networkid",
    "typedef/index.html#static-typedef-Event:bufferview.networkid",
    "src/libquassel.js~Event:bufferview.networkid",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.orderchanged",
    "typedef/index.html#static-typedef-Event:bufferview.orderchanged",
    "src/libquassel.js~Event:bufferview.orderchanged",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.search",
    "typedef/index.html#static-typedef-Event:bufferview.search",
    "src/libquassel.js~Event:bufferview.search",
    "typedef"
  ],
  [
    "src/libquassel.js~event:bufferview.update",
    "typedef/index.html#static-typedef-Event:bufferview.update",
    "src/libquassel.js~Event:bufferview.update",
    "typedef"
  ],
  [
    "src/libquassel.js~event:channel.addusermode",
    "typedef/index.html#static-typedef-Event:channel.addusermode",
    "src/libquassel.js~Event:channel.addusermode",
    "typedef"
  ],
  [
    "src/libquassel.js~event:channel.join",
    "typedef/index.html#static-typedef-Event:channel.join",
    "src/libquassel.js~Event:channel.join",
    "typedef"
  ],
  [
    "src/libquassel.js~event:channel.removeusermode",
    "typedef/index.html#static-typedef-Event:channel.removeusermode",
    "src/libquassel.js~Event:channel.removeusermode",
    "typedef"
  ],
  [
    "src/libquassel.js~event:channel.topic",
    "typedef/index.html#static-typedef-Event:channel.topic",
    "src/libquassel.js~Event:channel.topic",
    "typedef"
  ],
  [
    "src/libquassel.js~event:coreinfo",
    "typedef/index.html#static-typedef-Event:coreinfo",
    "src/libquassel.js~Event:coreinfo",
    "typedef"
  ],
  [
    "src/libquassel.js~event:coreinfoinit",
    "typedef/index.html#static-typedef-Event:coreinfoinit",
    "src/libquassel.js~Event:coreinfoinit",
    "typedef"
  ],
  [
    "src/libquassel.js~event:error",
    "typedef/index.html#static-typedef-Event:error",
    "src/libquassel.js~Event:error",
    "typedef"
  ],
  [
    "src/libquassel.js~event:identities.init",
    "typedef/index.html#static-typedef-Event:identities.init",
    "src/libquassel.js~Event:identities.init",
    "typedef"
  ],
  [
    "src/libquassel.js~event:identity",
    "typedef/index.html#static-typedef-Event:identity",
    "src/libquassel.js~Event:identity",
    "typedef"
  ],
  [
    "src/libquassel.js~event:identity.new",
    "typedef/index.html#static-typedef-Event:identity.new",
    "src/libquassel.js~Event:identity.new",
    "typedef"
  ],
  [
    "src/libquassel.js~event:identity.remove",
    "typedef/index.html#static-typedef-Event:identity.remove",
    "src/libquassel.js~Event:identity.remove",
    "typedef"
  ],
  [
    "src/libquassel.js~event:ignorelist",
    "typedef/index.html#static-typedef-Event:ignorelist",
    "src/libquassel.js~Event:ignorelist",
    "typedef"
  ],
  [
    "src/libquassel.js~event:init",
    "typedef/index.html#static-typedef-Event:init",
    "src/libquassel.js~Event:init",
    "typedef"
  ],
  [
    "src/libquassel.js~event:login",
    "typedef/index.html#static-typedef-Event:login",
    "src/libquassel.js~Event:login",
    "typedef"
  ],
  [
    "src/libquassel.js~event:loginfailed",
    "typedef/index.html#static-typedef-Event:loginfailed",
    "src/libquassel.js~Event:loginfailed",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.addbuffer",
    "typedef/index.html#static-typedef-Event:network.addbuffer",
    "src/libquassel.js~Event:network.addbuffer",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.adduser",
    "typedef/index.html#static-typedef-Event:network.adduser",
    "src/libquassel.js~Event:network.adduser",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.autoidentify.password",
    "typedef/index.html#static-typedef-Event:network.autoidentify.password",
    "src/libquassel.js~Event:network.autoidentify.password",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.autoidentify.service",
    "typedef/index.html#static-typedef-Event:network.autoidentify.service",
    "src/libquassel.js~Event:network.autoidentify.service",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.autoreconnect.interval",
    "typedef/index.html#static-typedef-Event:network.autoreconnect.interval",
    "src/libquassel.js~Event:network.autoreconnect.interval",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.autoreconnect.retries",
    "typedef/index.html#static-typedef-Event:network.autoreconnect.retries",
    "src/libquassel.js~Event:network.autoreconnect.retries",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.codec.decoding",
    "typedef/index.html#static-typedef-Event:network.codec.decoding",
    "src/libquassel.js~Event:network.codec.decoding",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.codec.encoding",
    "typedef/index.html#static-typedef-Event:network.codec.encoding",
    "src/libquassel.js~Event:network.codec.encoding",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.codec.server",
    "typedef/index.html#static-typedef-Event:network.codec.server",
    "src/libquassel.js~Event:network.codec.server",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.connected",
    "typedef/index.html#static-typedef-Event:network.connected",
    "src/libquassel.js~Event:network.connected",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.connectionstate",
    "typedef/index.html#static-typedef-Event:network.connectionstate",
    "src/libquassel.js~Event:network.connectionstate",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.disconnected",
    "typedef/index.html#static-typedef-Event:network.disconnected",
    "src/libquassel.js~Event:network.disconnected",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.identity",
    "typedef/index.html#static-typedef-Event:network.identity",
    "src/libquassel.js~Event:network.identity",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.init",
    "typedef/index.html#static-typedef-Event:network.init",
    "src/libquassel.js~Event:network.init",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.latency",
    "typedef/index.html#static-typedef-Event:network.latency",
    "src/libquassel.js~Event:network.latency",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.messagerate.burstsize",
    "typedef/index.html#static-typedef-Event:network.messagerate.burstsize",
    "src/libquassel.js~Event:network.messagerate.burstsize",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.messagerate.delay",
    "typedef/index.html#static-typedef-Event:network.messagerate.delay",
    "src/libquassel.js~Event:network.messagerate.delay",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.messagerate.unlimited",
    "typedef/index.html#static-typedef-Event:network.messagerate.unlimited",
    "src/libquassel.js~Event:network.messagerate.unlimited",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.mynick",
    "typedef/index.html#static-typedef-Event:network.mynick",
    "src/libquassel.js~Event:network.mynick",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.networkname",
    "typedef/index.html#static-typedef-Event:network.networkname",
    "src/libquassel.js~Event:network.networkname",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.new",
    "typedef/index.html#static-typedef-Event:network.new",
    "src/libquassel.js~Event:network.new",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.perform",
    "typedef/index.html#static-typedef-Event:network.perform",
    "src/libquassel.js~Event:network.perform",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.rejoinchannels",
    "typedef/index.html#static-typedef-Event:network.rejoinchannels",
    "src/libquassel.js~Event:network.rejoinchannels",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.remove",
    "typedef/index.html#static-typedef-Event:network.remove",
    "src/libquassel.js~Event:network.remove",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.sasl.account",
    "typedef/index.html#static-typedef-Event:network.sasl.account",
    "src/libquassel.js~Event:network.sasl.account",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.sasl.password",
    "typedef/index.html#static-typedef-Event:network.sasl.password",
    "src/libquassel.js~Event:network.sasl.password",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.server",
    "typedef/index.html#static-typedef-Event:network.server",
    "src/libquassel.js~Event:network.server",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.serverlist",
    "typedef/index.html#static-typedef-Event:network.serverlist",
    "src/libquassel.js~Event:network.serverlist",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.unlimitedreconnectretries",
    "typedef/index.html#static-typedef-Event:network.unlimitedreconnectretries",
    "src/libquassel.js~Event:network.unlimitedreconnectretries",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.usecustommessagerate",
    "typedef/index.html#static-typedef-Event:network.usecustommessagerate",
    "src/libquassel.js~Event:network.usecustommessagerate",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.userrenamed",
    "typedef/index.html#static-typedef-Event:network.userrenamed",
    "src/libquassel.js~Event:network.userrenamed",
    "typedef"
  ],
  [
    "src/libquassel.js~event:network.usesasl",
    "typedef/index.html#static-typedef-Event:network.usesasl",
    "src/libquassel.js~Event:network.usesasl",
    "typedef"
  ],
  [
    "src/libquassel.js~event:setup",
    "typedef/index.html#static-typedef-Event:setup",
    "src/libquassel.js~Event:setup",
    "typedef"
  ],
  [
    "src/libquassel.js~event:setupfailed",
    "typedef/index.html#static-typedef-Event:setupfailed",
    "src/libquassel.js~Event:setupfailed",
    "typedef"
  ],
  [
    "src/libquassel.js~event:setupok",
    "typedef/index.html#static-typedef-Event:setupok",
    "src/libquassel.js~Event:setupok",
    "typedef"
  ],
  [
    "src/libquassel.js~event:unhandled",
    "typedef/index.html#static-typedef-Event:unhandled",
    "src/libquassel.js~Event:unhandled",
    "typedef"
  ],
  [
    "src/libquassel.js~event:user.away",
    "typedef/index.html#static-typedef-Event:user.away",
    "src/libquassel.js~Event:user.away",
    "typedef"
  ],
  [
    "src/libquassel.js~event:user.part",
    "typedef/index.html#static-typedef-Event:user.part",
    "src/libquassel.js~Event:user.part",
    "typedef"
  ],
  [
    "src/libquassel.js~event:user.quit",
    "typedef/index.html#static-typedef-Event:user.quit",
    "src/libquassel.js~Event:user.quit",
    "typedef"
  ],
  [
    "src/libquassel.js~event:user.realname",
    "typedef/index.html#static-typedef-Event:user.realname",
    "src/libquassel.js~Event:user.realname",
    "typedef"
  ],
  [
    "src/libquassel.js~logincallback",
    "typedef/index.html#static-typedef-loginCallback",
    "src/libquassel.js~loginCallback",
    "typedef"
  ],
  [
    "src/message.js",
    "file/src/message.js.html",
    "src/message.js",
    "file"
  ],
  [
    "src/message.js~ircmessage#_flags",
    "class/src/message.js~IRCMessage.html#instance-member-_flags",
    "src/message.js~IRCMessage#_flags",
    "member"
  ],
  [
    "src/message.js~ircmessage#_sender",
    "class/src/message.js~IRCMessage.html#instance-member-_sender",
    "src/message.js~IRCMessage#_sender",
    "member"
  ],
  [
    "src/message.js~ircmessage#_updateflags",
    "class/src/message.js~IRCMessage.html#instance-method-_updateFlags",
    "src/message.js~IRCMessage#_updateFlags",
    "method"
  ],
  [
    "src/message.js~ircmessage#bufferinfo",
    "class/src/message.js~IRCMessage.html#instance-member-bufferInfo",
    "src/message.js~IRCMessage#bufferInfo",
    "member"
  ],
  [
    "src/message.js~ircmessage#constructor",
    "class/src/message.js~IRCMessage.html#instance-constructor-constructor",
    "src/message.js~IRCMessage#constructor",
    "method"
  ],
  [
    "src/message.js~ircmessage#content",
    "class/src/message.js~IRCMessage.html#instance-member-content",
    "src/message.js~IRCMessage#content",
    "member"
  ],
  [
    "src/message.js~ircmessage#datetime",
    "class/src/message.js~IRCMessage.html#instance-member-datetime",
    "src/message.js~IRCMessage#datetime",
    "member"
  ],
  [
    "src/message.js~ircmessage#flags",
    "class/src/message.js~IRCMessage.html#instance-set-flags",
    "src/message.js~IRCMessage#flags",
    "member"
  ],
  [
    "src/message.js~ircmessage#flags",
    "class/src/message.js~IRCMessage.html#instance-get-flags",
    "src/message.js~IRCMessage#flags",
    "member"
  ],
  [
    "src/message.js~ircmessage#hostmask",
    "class/src/message.js~IRCMessage.html#instance-member-hostmask",
    "src/message.js~IRCMessage#hostmask",
    "member"
  ],
  [
    "src/message.js~ircmessage#id",
    "class/src/message.js~IRCMessage.html#instance-member-id",
    "src/message.js~IRCMessage#id",
    "member"
  ],
  [
    "src/message.js~ircmessage#ishighlighted",
    "class/src/message.js~IRCMessage.html#instance-member-isHighlighted",
    "src/message.js~IRCMessage#isHighlighted",
    "member"
  ],
  [
    "src/message.js~ircmessage#isself",
    "class/src/message.js~IRCMessage.html#instance-member-isSelf",
    "src/message.js~IRCMessage#isSelf",
    "member"
  ],
  [
    "src/message.js~ircmessage#nick",
    "class/src/message.js~IRCMessage.html#instance-member-nick",
    "src/message.js~IRCMessage#nick",
    "member"
  ],
  [
    "src/message.js~ircmessage#sender",
    "class/src/message.js~IRCMessage.html#instance-get-sender",
    "src/message.js~IRCMessage#sender",
    "member"
  ],
  [
    "src/message.js~ircmessage#sender",
    "class/src/message.js~IRCMessage.html#instance-set-sender",
    "src/message.js~IRCMessage#sender",
    "member"
  ],
  [
    "src/message.js~ircmessage#tostring",
    "class/src/message.js~IRCMessage.html#instance-method-toString",
    "src/message.js~IRCMessage#toString",
    "method"
  ],
  [
    "src/message.js~ircmessage#type",
    "class/src/message.js~IRCMessage.html#instance-member-type",
    "src/message.js~IRCMessage#type",
    "member"
  ],
  [
    "src/network.js",
    "file/src/network.js.html",
    "src/network.js",
    "file"
  ],
  [
    "src/network.js~network#serverlist",
    "class/src/network.js~Network.html#instance-member-ServerList",
    "src/network.js~Network#ServerList",
    "member"
  ],
  [
    "src/network.js~network#_isconnected",
    "class/src/network.js~Network.html#instance-member-_isConnected",
    "src/network.js~Network#_isConnected",
    "member"
  ],
  [
    "src/network.js~network#_nick",
    "class/src/network.js~Network.html#instance-member-_nick",
    "src/network.js~Network#_nick",
    "member"
  ],
  [
    "src/network.js~network#adduser",
    "class/src/network.js~Network.html#instance-method-addUser",
    "src/network.js~Network#addUser",
    "method"
  ],
  [
    "src/network.js~network#autoidentifypassword",
    "class/src/network.js~Network.html#instance-member-autoIdentifyPassword",
    "src/network.js~Network#autoIdentifyPassword",
    "member"
  ],
  [
    "src/network.js~network#autoidentifyservice",
    "class/src/network.js~Network.html#instance-member-autoIdentifyService",
    "src/network.js~Network#autoIdentifyService",
    "member"
  ],
  [
    "src/network.js~network#autoreconnectinterval",
    "class/src/network.js~Network.html#instance-member-autoReconnectInterval",
    "src/network.js~Network#autoReconnectInterval",
    "member"
  ],
  [
    "src/network.js~network#autoreconnectretries",
    "class/src/network.js~Network.html#instance-member-autoReconnectRetries",
    "src/network.js~Network#autoReconnectRetries",
    "member"
  ],
  [
    "src/network.js~network#buffers",
    "class/src/network.js~Network.html#instance-member-buffers",
    "src/network.js~Network#buffers",
    "member"
  ],
  [
    "src/network.js~network#codecfordecoding",
    "class/src/network.js~Network.html#instance-member-codecForDecoding",
    "src/network.js~Network#codecForDecoding",
    "member"
  ],
  [
    "src/network.js~network#codecforencoding",
    "class/src/network.js~Network.html#instance-member-codecForEncoding",
    "src/network.js~Network#codecForEncoding",
    "member"
  ],
  [
    "src/network.js~network#codecforserver",
    "class/src/network.js~Network.html#instance-member-codecForServer",
    "src/network.js~Network#codecForServer",
    "member"
  ],
  [
    "src/network.js~network#connectionstate",
    "class/src/network.js~Network.html#instance-member-connectionState",
    "src/network.js~Network#connectionState",
    "member"
  ],
  [
    "src/network.js~network#constructor",
    "class/src/network.js~Network.html#instance-constructor-constructor",
    "src/network.js~Network#constructor",
    "method"
  ],
  [
    "src/network.js~network#deleteuser",
    "class/src/network.js~Network.html#instance-method-deleteUser",
    "src/network.js~Network#deleteUser",
    "method"
  ],
  [
    "src/network.js~network#getbuffer",
    "class/src/network.js~Network.html#instance-method-getBuffer",
    "src/network.js~Network#getBuffer",
    "method"
  ],
  [
    "src/network.js~network#getuser",
    "class/src/network.js~Network.html#instance-method-getUser",
    "src/network.js~Network#getUser",
    "method"
  ],
  [
    "src/network.js~network#hasbuffer",
    "class/src/network.js~Network.html#instance-method-hasBuffer",
    "src/network.js~Network#hasBuffer",
    "method"
  ],
  [
    "src/network.js~network#hasuser",
    "class/src/network.js~Network.html#instance-method-hasUser",
    "src/network.js~Network#hasUser",
    "method"
  ],
  [
    "src/network.js~network#id",
    "class/src/network.js~Network.html#instance-member-id",
    "src/network.js~Network#id",
    "member"
  ],
  [
    "src/network.js~network#identityid",
    "class/src/network.js~Network.html#instance-member-identityId",
    "src/network.js~Network#identityId",
    "member"
  ],
  [
    "src/network.js~network#ircusersandchannels",
    "class/src/network.js~Network.html#instance-set-ircUsersAndChannels",
    "src/network.js~Network#ircUsersAndChannels",
    "member"
  ],
  [
    "src/network.js~network#isconnected",
    "class/src/network.js~Network.html#instance-get-isConnected",
    "src/network.js~Network#isConnected",
    "member"
  ],
  [
    "src/network.js~network#isconnected",
    "class/src/network.js~Network.html#instance-set-isConnected",
    "src/network.js~Network#isConnected",
    "member"
  ],
  [
    "src/network.js~network#latency",
    "class/src/network.js~Network.html#instance-member-latency",
    "src/network.js~Network#latency",
    "member"
  ],
  [
    "src/network.js~network#msgrateburstsize",
    "class/src/network.js~Network.html#instance-member-msgRateBurstSize",
    "src/network.js~Network#msgRateBurstSize",
    "member"
  ],
  [
    "src/network.js~network#msgratemessagedelay",
    "class/src/network.js~Network.html#instance-member-msgRateMessageDelay",
    "src/network.js~Network#msgRateMessageDelay",
    "member"
  ],
  [
    "src/network.js~network#mynick",
    "class/src/network.js~Network.html#instance-set-myNick",
    "src/network.js~Network#myNick",
    "member"
  ],
  [
    "src/network.js~network#mynick",
    "class/src/network.js~Network.html#instance-get-myNick",
    "src/network.js~Network#myNick",
    "member"
  ],
  [
    "src/network.js~network#name",
    "class/src/network.js~Network.html#instance-member-name",
    "src/network.js~Network#name",
    "member"
  ],
  [
    "src/network.js~network#networkid",
    "class/src/network.js~Network.html#instance-set-networkId",
    "src/network.js~Network#networkId",
    "member"
  ],
  [
    "src/network.js~network#networkid",
    "class/src/network.js~Network.html#instance-get-networkId",
    "src/network.js~Network#networkId",
    "member"
  ],
  [
    "src/network.js~network#networkname",
    "class/src/network.js~Network.html#instance-set-networkName",
    "src/network.js~Network#networkName",
    "member"
  ],
  [
    "src/network.js~network#networkname",
    "class/src/network.js~Network.html#instance-get-networkName",
    "src/network.js~Network#networkName",
    "member"
  ],
  [
    "src/network.js~network#nick",
    "class/src/network.js~Network.html#instance-get-nick",
    "src/network.js~Network#nick",
    "member"
  ],
  [
    "src/network.js~network#nick",
    "class/src/network.js~Network.html#instance-set-nick",
    "src/network.js~Network#nick",
    "member"
  ],
  [
    "src/network.js~network#nickregex",
    "class/src/network.js~Network.html#instance-member-nickRegex",
    "src/network.js~Network#nickRegex",
    "member"
  ],
  [
    "src/network.js~network#open",
    "class/src/network.js~Network.html#instance-member-open",
    "src/network.js~Network#open",
    "member"
  ],
  [
    "src/network.js~network#perform",
    "class/src/network.js~Network.html#instance-member-perform",
    "src/network.js~Network#perform",
    "member"
  ],
  [
    "src/network.js~network#rejoinchannels",
    "class/src/network.js~Network.html#instance-member-rejoinChannels",
    "src/network.js~Network#rejoinChannels",
    "member"
  ],
  [
    "src/network.js~network#renameuser",
    "class/src/network.js~Network.html#instance-method-renameUser",
    "src/network.js~Network#renameUser",
    "method"
  ],
  [
    "src/network.js~network#saslaccount",
    "class/src/network.js~Network.html#instance-member-saslAccount",
    "src/network.js~Network#saslAccount",
    "member"
  ],
  [
    "src/network.js~network#saslpassword",
    "class/src/network.js~Network.html#instance-member-saslPassword",
    "src/network.js~Network#saslPassword",
    "member"
  ],
  [
    "src/network.js~network#statusbuffer",
    "class/src/network.js~Network.html#instance-member-statusBuffer",
    "src/network.js~Network#statusBuffer",
    "member"
  ],
  [
    "src/network.js~network#tostring",
    "class/src/network.js~Network.html#instance-method-toString",
    "src/network.js~Network#toString",
    "method"
  ],
  [
    "src/network.js~network#unlimitedmessagerate",
    "class/src/network.js~Network.html#instance-member-unlimitedMessageRate",
    "src/network.js~Network#unlimitedMessageRate",
    "member"
  ],
  [
    "src/network.js~network#unlimitedreconnectretries",
    "class/src/network.js~Network.html#instance-member-unlimitedReconnectRetries",
    "src/network.js~Network#unlimitedReconnectRetries",
    "member"
  ],
  [
    "src/network.js~network#update",
    "class/src/network.js~Network.html#instance-method-update",
    "src/network.js~Network#update",
    "method"
  ],
  [
    "src/network.js~network#updateusers",
    "class/src/network.js~Network.html#instance-method-updateUsers",
    "src/network.js~Network#updateUsers",
    "method"
  ],
  [
    "src/network.js~network#useautoidentify",
    "class/src/network.js~Network.html#instance-member-useAutoIdentify",
    "src/network.js~Network#useAutoIdentify",
    "member"
  ],
  [
    "src/network.js~network#useautoreconnect",
    "class/src/network.js~Network.html#instance-member-useAutoReconnect",
    "src/network.js~Network#useAutoReconnect",
    "member"
  ],
  [
    "src/network.js~network#usecustommessagerate",
    "class/src/network.js~Network.html#instance-member-useCustomMessageRate",
    "src/network.js~Network#useCustomMessageRate",
    "member"
  ],
  [
    "src/network.js~network#userandomserver",
    "class/src/network.js~Network.html#instance-member-useRandomServer",
    "src/network.js~Network#useRandomServer",
    "member"
  ],
  [
    "src/network.js~network#usesasl",
    "class/src/network.js~Network.html#instance-member-useSasl",
    "src/network.js~Network#useSasl",
    "member"
  ],
  [
    "src/network.js~network#users",
    "class/src/network.js~Network.html#instance-member-users",
    "src/network.js~Network#users",
    "member"
  ],
  [
    "src/network.js~networkcollection#add",
    "class/src/network.js~NetworkCollection.html#instance-method-add",
    "src/network.js~NetworkCollection#add",
    "method"
  ],
  [
    "src/network.js~networkcollection#buffers",
    "class/src/network.js~NetworkCollection.html#instance-method-buffers",
    "src/network.js~NetworkCollection#buffers",
    "method"
  ],
  [
    "src/network.js~networkcollection#deletebuffer",
    "class/src/network.js~NetworkCollection.html#instance-method-deleteBuffer",
    "src/network.js~NetworkCollection#deleteBuffer",
    "method"
  ],
  [
    "src/network.js~networkcollection#getbuffer",
    "class/src/network.js~NetworkCollection.html#instance-method-getBuffer",
    "src/network.js~NetworkCollection#getBuffer",
    "method"
  ],
  [
    "src/network.js~networkcollection#hasbuffer",
    "class/src/network.js~NetworkCollection.html#instance-method-hasBuffer",
    "src/network.js~NetworkCollection#hasBuffer",
    "method"
  ],
  [
    "src/network.js~server#constructor",
    "class/src/network.js~Server.html#instance-constructor-constructor",
    "src/network.js~Server#constructor",
    "method"
  ],
  [
    "src/network.js~server#host",
    "class/src/network.js~Server.html#instance-member-host",
    "src/network.js~Server#host",
    "member"
  ],
  [
    "src/network.js~server#password",
    "class/src/network.js~Server.html#instance-member-password",
    "src/network.js~Server#password",
    "member"
  ],
  [
    "src/network.js~server#port",
    "class/src/network.js~Server.html#instance-member-port",
    "src/network.js~Server#port",
    "member"
  ],
  [
    "src/network.js~server#proxyhost",
    "class/src/network.js~Server.html#instance-member-proxyHost",
    "src/network.js~Server#proxyHost",
    "member"
  ],
  [
    "src/network.js~server#proxypass",
    "class/src/network.js~Server.html#instance-member-proxyPass",
    "src/network.js~Server#proxyPass",
    "member"
  ],
  [
    "src/network.js~server#proxyport",
    "class/src/network.js~Server.html#instance-member-proxyPort",
    "src/network.js~Server#proxyPort",
    "member"
  ],
  [
    "src/network.js~server#proxytype",
    "class/src/network.js~Server.html#instance-member-proxyType",
    "src/network.js~Server#proxyType",
    "member"
  ],
  [
    "src/network.js~server#proxyuser",
    "class/src/network.js~Server.html#instance-member-proxyUser",
    "src/network.js~Server#proxyUser",
    "member"
  ],
  [
    "src/network.js~server#sslverify",
    "class/src/network.js~Server.html#instance-member-sslVerify",
    "src/network.js~Server#sslVerify",
    "member"
  ],
  [
    "src/network.js~server#sslversion",
    "class/src/network.js~Server.html#instance-member-sslVersion",
    "src/network.js~Server#sslVersion",
    "member"
  ],
  [
    "src/network.js~server#useproxy",
    "class/src/network.js~Server.html#instance-member-useProxy",
    "src/network.js~Server#useProxy",
    "member"
  ],
  [
    "src/network.js~server#usessl",
    "class/src/network.js~Server.html#instance-member-useSSL",
    "src/network.js~Server#useSSL",
    "member"
  ],
  [
    "src/request.js",
    "file/src/request.js.html",
    "src/request.js",
    "file"
  ],
  [
    "src/request.js~core#backlog",
    "class/src/request.js~Core.html#instance-method-backlog",
    "src/request.js~Core#backlog",
    "method"
  ],
  [
    "src/request.js~core#connect",
    "class/src/request.js~Core.html#instance-method-connect",
    "src/request.js~Core#connect",
    "method"
  ],
  [
    "src/request.js~core#connectnetwork",
    "class/src/request.js~Core.html#instance-method-connectNetwork",
    "src/request.js~Core#connectNetwork",
    "method"
  ],
  [
    "src/request.js~core#constructor",
    "class/src/request.js~Core.html#instance-constructor-constructor",
    "src/request.js~Core#constructor",
    "method"
  ],
  [
    "src/request.js~core#createbufferview",
    "class/src/request.js~Core.html#instance-method-createBufferView",
    "src/request.js~Core#createBufferView",
    "method"
  ],
  [
    "src/request.js~core#createidentity",
    "class/src/request.js~Core.html#instance-method-createIdentity",
    "src/request.js~Core#createIdentity",
    "method"
  ],
  [
    "src/request.js~core#createnetwork",
    "class/src/request.js~Core.html#instance-method-createNetwork",
    "src/request.js~Core#createNetwork",
    "method"
  ],
  [
    "src/request.js~core#disconnect",
    "class/src/request.js~Core.html#instance-method-disconnect",
    "src/request.js~Core#disconnect",
    "method"
  ],
  [
    "src/request.js~core#disconnectnetwork",
    "class/src/request.js~Core.html#instance-method-disconnectNetwork",
    "src/request.js~Core#disconnectNetwork",
    "method"
  ],
  [
    "src/request.js~core#duplex",
    "class/src/request.js~Core.html#instance-member-duplex",
    "src/request.js~Core#duplex",
    "member"
  ],
  [
    "src/request.js~core#finishclientinit",
    "class/src/request.js~Core.html#instance-method-finishClientInit",
    "src/request.js~Core#finishClientInit",
    "method"
  ],
  [
    "src/request.js~core#heartbeat",
    "class/src/request.js~Core.html#instance-method-heartBeat",
    "src/request.js~Core#heartBeat",
    "method"
  ],
  [
    "src/request.js~core#hidebufferpermanently",
    "class/src/request.js~Core.html#instance-method-hideBufferPermanently",
    "src/request.js~Core#hideBufferPermanently",
    "method"
  ],
  [
    "src/request.js~core#hidebuffertemporarily",
    "class/src/request.js~Core.html#instance-method-hideBufferTemporarily",
    "src/request.js~Core#hideBufferTemporarily",
    "method"
  ],
  [
    "src/request.js~core#init",
    "class/src/request.js~Core.html#instance-method-init",
    "src/request.js~Core#init",
    "method"
  ],
  [
    "src/request.js~core#login",
    "class/src/request.js~Core.html#instance-method-login",
    "src/request.js~Core#login",
    "method"
  ],
  [
    "src/request.js~core#markbufferasread",
    "class/src/request.js~Core.html#instance-method-markBufferAsRead",
    "src/request.js~Core#markBufferAsRead",
    "method"
  ],
  [
    "src/request.js~core#mergebufferspermanently",
    "class/src/request.js~Core.html#instance-method-mergeBuffersPermanently",
    "src/request.js~Core#mergeBuffersPermanently",
    "method"
  ],
  [
    "src/request.js~core#options",
    "class/src/request.js~Core.html#instance-member-options",
    "src/request.js~Core#options",
    "member"
  ],
  [
    "src/request.js~core#purgebufferids",
    "class/src/request.js~Core.html#instance-method-purgeBufferIds",
    "src/request.js~Core#purgeBufferIds",
    "method"
  ],
  [
    "src/request.js~core#qtsocket",
    "class/src/request.js~Core.html#instance-member-qtsocket",
    "src/request.js~Core#qtsocket",
    "member"
  ],
  [
    "src/request.js~core#removebuffer",
    "class/src/request.js~Core.html#instance-method-removeBuffer",
    "src/request.js~Core#removeBuffer",
    "method"
  ],
  [
    "src/request.js~core#removeidentity",
    "class/src/request.js~Core.html#instance-method-removeIdentity",
    "src/request.js~Core#removeIdentity",
    "method"
  ],
  [
    "src/request.js~core#removenetwork",
    "class/src/request.js~Core.html#instance-method-removeNetwork",
    "src/request.js~Core#removeNetwork",
    "method"
  ],
  [
    "src/request.js~core#renamebuffer",
    "class/src/request.js~Core.html#instance-method-renameBuffer",
    "src/request.js~Core#renameBuffer",
    "method"
  ],
  [
    "src/request.js~core#sendclientinfo",
    "class/src/request.js~Core.html#instance-method-sendClientInfo",
    "src/request.js~Core#sendClientInfo",
    "method"
  ],
  [
    "src/request.js~core#sendinitrequest",
    "class/src/request.js~Core.html#instance-method-sendInitRequest",
    "src/request.js~Core#sendInitRequest",
    "method"
  ],
  [
    "src/request.js~core#sendmessage",
    "class/src/request.js~Core.html#instance-method-sendMessage",
    "src/request.js~Core#sendMessage",
    "method"
  ],
  [
    "src/request.js~core#setlastmsgread",
    "class/src/request.js~Core.html#instance-method-setLastMsgRead",
    "src/request.js~Core#setLastMsgRead",
    "method"
  ],
  [
    "src/request.js~core#setmarkerline",
    "class/src/request.js~Core.html#instance-method-setMarkerLine",
    "src/request.js~Core#setMarkerLine",
    "method"
  ],
  [
    "src/request.js~core#setnetworkinfo",
    "class/src/request.js~Core.html#instance-method-setNetworkInfo",
    "src/request.js~Core#setNetworkInfo",
    "method"
  ],
  [
    "src/request.js~core#setupcore",
    "class/src/request.js~Core.html#instance-method-setupCore",
    "src/request.js~Core#setupCore",
    "method"
  ],
  [
    "src/request.js~core#unhidebuffer",
    "class/src/request.js~Core.html#instance-method-unhideBuffer",
    "src/request.js~Core#unhideBuffer",
    "method"
  ],
  [
    "src/request.js~core#updatealiasmanager",
    "class/src/request.js~Core.html#instance-method-updateAliasManager",
    "src/request.js~Core#updateAliasManager",
    "method"
  ],
  [
    "src/request.js~core#updateidentity",
    "class/src/request.js~Core.html#instance-method-updateIdentity",
    "src/request.js~Core#updateIdentity",
    "method"
  ],
  [
    "src/request.js~core#updateignorelistmanager",
    "class/src/request.js~Core.html#instance-method-updateIgnoreListManager",
    "src/request.js~Core#updateIgnoreListManager",
    "method"
  ],
  [
    "src/request.js~core#usecompression",
    "class/src/request.js~Core.html#instance-member-useCompression",
    "src/request.js~Core#useCompression",
    "member"
  ],
  [
    "src/request.js~core#usessl",
    "class/src/request.js~Core.html#instance-member-useSSL",
    "src/request.js~Core#useSSL",
    "member"
  ],
  [
    "src/tls.js",
    "file/src/tls.js.html",
    "src/tls.js",
    "file"
  ],
  [
    "src/user.js",
    "file/src/user.js.html",
    "src/user.js",
    "file"
  ],
  [
    "src/user.js~ircuser#_id",
    "class/src/user.js~IRCUser.html#instance-member-_id",
    "src/user.js~IRCUser#_id",
    "member"
  ],
  [
    "src/user.js~ircuser#away",
    "class/src/user.js~IRCUser.html#instance-member-away",
    "src/user.js~IRCUser#away",
    "member"
  ],
  [
    "src/user.js~ircuser#awaymessage",
    "class/src/user.js~IRCUser.html#instance-member-awayMessage",
    "src/user.js~IRCUser#awayMessage",
    "member"
  ],
  [
    "src/user.js~ircuser#channels",
    "class/src/user.js~IRCUser.html#instance-member-channels",
    "src/user.js~IRCUser#channels",
    "member"
  ],
  [
    "src/user.js~ircuser#constructor",
    "class/src/user.js~IRCUser.html#instance-constructor-constructor",
    "src/user.js~IRCUser#constructor",
    "method"
  ],
  [
    "src/user.js~ircuser#encrypted",
    "class/src/user.js~IRCUser.html#instance-member-encrypted",
    "src/user.js~IRCUser#encrypted",
    "member"
  ],
  [
    "src/user.js~ircuser#host",
    "class/src/user.js~IRCUser.html#instance-member-host",
    "src/user.js~IRCUser#host",
    "member"
  ],
  [
    "src/user.js~ircuser#id",
    "class/src/user.js~IRCUser.html#instance-get-id",
    "src/user.js~IRCUser#id",
    "member"
  ],
  [
    "src/user.js~ircuser#id",
    "class/src/user.js~IRCUser.html#instance-set-id",
    "src/user.js~IRCUser#id",
    "member"
  ],
  [
    "src/user.js~ircuser#idletime",
    "class/src/user.js~IRCUser.html#instance-member-idleTime",
    "src/user.js~IRCUser#idleTime",
    "member"
  ],
  [
    "src/user.js~ircuser#ircoperator",
    "class/src/user.js~IRCUser.html#instance-member-ircOperator",
    "src/user.js~IRCUser#ircOperator",
    "member"
  ],
  [
    "src/user.js~ircuser#lastawaymessage",
    "class/src/user.js~IRCUser.html#instance-member-lastAwayMessage",
    "src/user.js~IRCUser#lastAwayMessage",
    "member"
  ],
  [
    "src/user.js~ircuser#logintime",
    "class/src/user.js~IRCUser.html#instance-member-loginTime",
    "src/user.js~IRCUser#loginTime",
    "member"
  ],
  [
    "src/user.js~ircuser#nick",
    "class/src/user.js~IRCUser.html#instance-member-nick",
    "src/user.js~IRCUser#nick",
    "member"
  ],
  [
    "src/user.js~ircuser#realname",
    "class/src/user.js~IRCUser.html#instance-member-realName",
    "src/user.js~IRCUser#realName",
    "member"
  ],
  [
    "src/user.js~ircuser#server",
    "class/src/user.js~IRCUser.html#instance-member-server",
    "src/user.js~IRCUser#server",
    "member"
  ],
  [
    "src/user.js~ircuser#update",
    "class/src/user.js~IRCUser.html#instance-method-update",
    "src/user.js~IRCUser#update",
    "method"
  ],
  [
    "src/user.js~ircuser#user",
    "class/src/user.js~IRCUser.html#instance-member-user",
    "src/user.js~IRCUser#user",
    "member"
  ],
  [
    "src/user.js~ircuser#userhost",
    "class/src/user.js~IRCUser.html#instance-member-userHost",
    "src/user.js~IRCUser#userHost",
    "member"
  ],
  [
    "src/user.js~ircuser#usermodes",
    "class/src/user.js~IRCUser.html#instance-member-userModes",
    "src/user.js~IRCUser#userModes",
    "member"
  ],
  [
    "src/user.js~ircuser#whoisservicereply",
    "class/src/user.js~IRCUser.html#instance-member-whoisServiceReply",
    "src/user.js~IRCUser#whoisServiceReply",
    "member"
  ],
  [
    "src/usertypes.js",
    "file/src/usertypes.js.html",
    "src/usertypes.js",
    "file"
  ],
  [
    "src/usertypes.js~usertype<bufferid>",
    "typedef/index.html#static-typedef-UserType<BufferId>",
    "src/usertypes.js~UserType<BufferId>",
    "typedef"
  ],
  [
    "src/usertypes.js~usertype<bufferinfo>",
    "typedef/index.html#static-typedef-UserType<BufferInfo>",
    "src/usertypes.js~UserType<BufferInfo>",
    "typedef"
  ],
  [
    "src/usertypes.js~usertype<identity>",
    "typedef/index.html#static-typedef-UserType<Identity>",
    "src/usertypes.js~UserType<Identity>",
    "typedef"
  ],
  [
    "src/usertypes.js~usertype<identityid>",
    "typedef/index.html#static-typedef-UserType<IdentityId>",
    "src/usertypes.js~UserType<IdentityId>",
    "typedef"
  ],
  [
    "src/usertypes.js~usertype<message>",
    "typedef/index.html#static-typedef-UserType<Message>",
    "src/usertypes.js~UserType<Message>",
    "typedef"
  ],
  [
    "src/usertypes.js~usertype<msgid>",
    "typedef/index.html#static-typedef-UserType<MsgId>",
    "src/usertypes.js~UserType<MsgId>",
    "typedef"
  ],
  [
    "src/usertypes.js~usertype<network::server>",
    "typedef/index.html#static-typedef-UserType<Network::Server>",
    "src/usertypes.js~UserType<Network::Server>",
    "typedef"
  ],
  [
    "src/usertypes.js~usertype<networkid>",
    "typedef/index.html#static-typedef-UserType<NetworkId>",
    "src/usertypes.js~UserType<NetworkId>",
    "typedef"
  ],
  [
    "src/usertypes.js~usertype<networkid>",
    "typedef/index.html#static-typedef-UserType<NetworkId>",
    "src/usertypes.js~UserType<NetworkId>",
    "typedef"
  ],
  [
    "src/usertypes.js~usertype<networkinfo>",
    "typedef/index.html#static-typedef-UserType<NetworkInfo>",
    "src/usertypes.js~UserType<NetworkInfo>",
    "typedef"
  ],
  [
    "src/websocket.js",
    "file/src/websocket.js.html",
    "src/websocket.js",
    "file"
  ],
  [
    "src/websocket.js~websocketstream#_read",
    "class/src/websocket.js~WebSocketStream.html#instance-method-_read",
    "src/websocket.js~WebSocketStream#_read",
    "method"
  ],
  [
    "src/websocket.js~websocketstream#_write",
    "class/src/websocket.js~WebSocketStream.html#instance-method-_write",
    "src/websocket.js~WebSocketStream#_write",
    "method"
  ],
  [
    "src/websocket.js~websocketstream#constructor",
    "class/src/websocket.js~WebSocketStream.html#instance-constructor-constructor",
    "src/websocket.js~WebSocketStream#constructor",
    "method"
  ],
  [
    "src/websocket.js~websocketstream#socket",
    "class/src/websocket.js~WebSocketStream.html#instance-member-socket",
    "src/websocket.js~WebSocketStream#socket",
    "member"
  ]
]